### ISSUE TITLE
Rasplex playing channels: always plays first item in playlist

### ISSUE THREAD

**Issue by avelicu** [RasPlex/RasPlex#311]
Hi,

Running Rasplex 1.4.1 with the latest OSX Plex Media Server. Movies and TV Series stream perfectly; however channels do not seem to work as they should.

I am able to reproduce this problem in 100% of the cases with the unofficial Spotify2 channel, as well as with the official Soundcloud channel.

Whenever I try to play something from the web app (either running locally or on plex.tv), when I am in a playlist view (an actual playlist, an artist view, an album view, etc), whatever track I choose, Rasplex will always play the first item in the playlist. For example, in one particular playlist in Spotify, I have the following items in the head:

1) Explosions in the Sky - Your Hand in Mine (spotify:track:69QoB2je3pKldFoxXuBOAu.mp3)
2) Explosions in the Sky - Remember Me as A Time of Day (spotify:track:3o6RpCtAPejVvTckcd5JVt.mp3)
3) Explosions in the Sky - A Song for our Fathers (spotify:track:4SBOJH1IRqVHAf5TviXspr.mp3)

When I connect to Rasplex, whether I double-click on 1, 2, or 3, 1 will always start playing.
Pressing Next or Previous succesfully navigates the playlist - however jumping directly to a track fails, and Rasplex always plays the first item in the playlist.

Serial number of your pi (new!): 00000000fa8ef777
Crash ID, if known - you can get this from the debug log if a crash was sent (new!): No crash.
Size of Raspberry Pi (256, 512): 512
Type of SD card (SDHC class 10?): SDHC unknown 4gb.
Internet connection type (Ethernet or Wifi): Ethernet
Version of RasPlex (if not the latest, please see if the problem exists on latest first): 1.4.1
Log files (ensure that you enable "debug logging in Preferences -> System -> advanced" and try to reproduce the issue): 

http://pastebin.com/sVW4zed2
Note: asking to play "spotify:track:3o6RpCtAPejVvTckcd5JVt.mp3", actually plays "spotify:track:69QoB2je3pKldFoxXuBOAu.mp3".

How did you install rasplex? (gui installer, win32 disk imager, what platform OSX/Win/Linux?): GUI Installer OSX
Best description you can give of the problem: Above
Steps to reproduce (what were you doing when it happened? Can you make it happen again?):
1) Install Spotify2 plugin in Plex Media Server
2) Navigate to a playlist
3) Ensure streaming to rasplex
4) Double-click second, third, nth item

EXPECTED:
Second, third, nth item starts playing

ACTUAL:
First item starts playing

**Comment by NedtheNerd** [comment]
Should be fixed in next release.

**Comment by NedtheNerd** [comment]
Fixed in latest release 0.5.0. Closing

**Comment by Nosskirneh** [comment]
I still have this issue, even though it's stated as fixed. This renders playing audio files useless on Rasplex for me. I'm using Rasplex 1.0.1.

**Comment by themaskedbear** [comment]
Hi,

Same issue here, using rasplex 1.0.3. With Spotify2 bundle, The first item is always played even if I've asked for another one. On the plex web interface (without sending on rasplex), this is working.
